version: '3.8'

# Minimal setup with just Neo4j for the basic Cognee MCP configuration
# Use this if you want to keep LanceDB and SQLite as embedded databases

services:
  # Neo4j Graph Database - Required for graph operations
  neo4j:
    image: neo4j:5.15
    container_name: neo4j-cognee-minimal
    environment:
      - NEO4J_AUTH=neo4j/password123
      - NEO4J_dbms_memory_heap_initial__size=256m
      - NEO4J_dbms_memory_heap_max__size=1G
    ports:
      - "7474:7474"  # Neo4j Browser
      - "7687:7687"  # Bolt protocol
    volumes:
      - neo4j_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "cypher-shell -u neo4j -p password123 'RETURN 1'"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  neo4j_data:
    driver: local